/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scaapp.gui;

import scaapp.pojo.EmployeeDetails;
import com.alee.laf.WebLookAndFeel;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.AbstractAction;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.KeyStroke;
import scaapp.dao.BatchDao;
import scaapp.dao.CourseDao;
import scaapp.dao.EmployeeDao;
import scaapp.pojo.BatchDetails;
import scaapp.utils.BatchIdGenerator;
import scaapp.utils.DisabledPanel;

/**
 *
 * @author Comp10
 */
public class AddBatchNew extends javax.swing.JFrame {
    private final AddBatchNew ens = this;
    /**
     * Creates new form EnrollNewStudent    /**
     * Creates new form EnrollNewStudent
     */
    
    EmployeeDetails ed;
    public AddBatchNew() {
        
        
        
        
        
        try {
            initComponents();
            //ArrayList<String> arr=SessionDao.getSession();
           // for(String str:arr)
                //awtSessionId.add("2017");
            ArrayList<String> list=CourseDao.getCourse();
            for(String s:list)
                awtCourse.addItem(s);
            
          
//            awtCourse.add("OCA");
//            awtCourse.add("ORACLE");
//            awtCourse.add("ANDROID");
//            awtCourse.add("PYTHON");
//            awtCourse.add("SPRING");
//            awtCourse.add("Hibernate");
//            awtCourse.add("PHP");
//            awtCourse.add("WEB DEVELOPMENT");
//            awtCourse.add("Data Structure");
            awtFaculty.addItem("Sachin Kapoor");
            awtFaculty.addItem("Paramjeet Singh");
            awtFaculty.addItem("Sanjeev Sharma");
            awtFaculty.addItem("Seema Sharma");
            awtCenter.addItem("Mansarovar");
            awtCenter.addItem("Indrapuri");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        setLocationRelativeTo(null);
        
        
        
        
        JPanel panel = (JPanel)this.getContentPane();
        InputMap im = panel.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        im.put(KeyStroke.getKeyStroke("ctrl pressed B"), "cB");
        panel.getActionMap().put("cB", new AbstractAction(){
            public void actionPerformed(ActionEvent e) {
                ens.hide();
            }
        });
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
        
    }

    AddBatchNew(EmployeeDetails ed) {
        this();
        this.ed=ed;
        employeeName.setText(ed.getEmp_name());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        awtCourse = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        awtStartDate = new com.toedter.calendar.JDateChooser();
        monday = new javax.swing.JCheckBox();
        tuesday = new javax.swing.JCheckBox();
        wednesday = new javax.swing.JCheckBox();
        thursday = new javax.swing.JCheckBox();
        friday = new javax.swing.JCheckBox();
        saturday = new javax.swing.JCheckBox();
        sunday = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        awtFaculty = new javax.swing.JComboBox();
        awtCenter = new javax.swing.JComboBox();
        pm = new javax.swing.JRadioButton();
        am = new javax.swing.JRadioButton();
        hh = new javax.swing.JComboBox();
        mm = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        employeeName = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Batch- SCAOnCloud v1.0.0");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Contact details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jLabel1.setText("Start time");

        awtCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                awtCourseActionPerformed(evt);
            }
        });
        awtCourse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                awtCourseKeyPressed(evt);
            }
        });

        jLabel9.setText("Course");

        jLabel14.setText("Date");

        awtStartDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                awtStartDateMouseClicked(evt);
            }
        });
        awtStartDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                awtStartDateKeyPressed(evt);
            }
        });

        monday.setText("Monday");

        tuesday.setText("Tuesday");

        wednesday.setText("Wednesday");

        thursday.setText("Thursday");

        friday.setText("Friday");

        saturday.setText("Saturday");

        sunday.setText("Sunday");

        jLabel11.setText("Select faculty");

        jLabel12.setText("Select centre");

        awtFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                awtFacultyActionPerformed(evt);
            }
        });
        awtFaculty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                awtFacultyKeyPressed(evt);
            }
        });

        awtCenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                awtCenterActionPerformed(evt);
            }
        });
        awtCenter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                awtCenterKeyPressed(evt);
            }
        });

        buttonGroup1.add(pm);
        pm.setSelected(true);
        pm.setText("PM");

        buttonGroup1.add(am);
        am.setText("AM");

        hh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "HH", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        mm.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MM", "00", "15", "30", "45", " " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(monday)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tuesday)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(wednesday)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(thursday)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(friday)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saturday)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sunday)
                        .addGap(34, 34, 34))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(awtCenter, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(awtFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(awtStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(awtCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(hh, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(mm, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(pm)
                                        .addGap(18, 18, 18)
                                        .addComponent(am)
                                        .addGap(38, 38, 38)))))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(awtCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(awtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pm)
                    .addComponent(am)
                    .addComponent(hh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monday)
                    .addComponent(tuesday)
                    .addComponent(wednesday)
                    .addComponent(thursday)
                    .addComponent(friday)
                    .addComponent(saturday)
                    .addComponent(sunday))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(awtFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(awtCenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jButton1.setText("Add Batch");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "User details"));

        jLabel16.setText("You are logged in as ");

        employeeName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        employeeName.setForeground(new java.awt.Color(0, 153, 51));
        employeeName.setText("Anonymous");

        jButton2.setText("Logout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(employeeName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(19, 19, 19))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(employeeName)
                    .addComponent(jButton2)
                    .addComponent(Back))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void awtCourseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_awtCourseKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            jButton1.requestFocus();
        }
    }//GEN-LAST:event_awtCourseKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         String days="";
        if(monday.isSelected())
        days+="M";
        if(tuesday.isSelected())
        days+="T";
        if(wednesday.isSelected())
        days+="W";
        if(thursday.isSelected())
        days+="Th";
        if(friday.isSelected())
        days+="F";
        if(saturday.isSelected())
        days+="St";
        if(sunday.isSelected())
        days+="S";
       // awtStartDate
          if(awtStartDate.getDate()==null){
            JOptionPane.showMessageDialog(null,"Please Select date","Error",JOptionPane.INFORMATION_MESSAGE);
            return;
        
        }       
         if(hh.getSelectedItem().toString().equalsIgnoreCase("hh")||mm.getSelectedItem().toString().equalsIgnoreCase("mm")){
            JOptionPane.showMessageDialog(null,"Please Select valid Time","Error",JOptionPane.INFORMATION_MESSAGE);
            return;
        
        }
        
        
        if(days.equals("")){
            JOptionPane.showMessageDialog(null,"Select atleast one day","Error",JOptionPane.INFORMATION_MESSAGE);
            return;
        
        }
        
        
        
       // System.out.println(days);
        try {
            // TODO add your handling code here:

            BatchDetails bd=new BatchDetails();
            BatchIdGenerator big=new BatchIdGenerator();
            bd.setBatch_centre(awtCenter.getSelectedIndex()+1);
            big.setCenter(awtCenter.getSelectedIndex()+1);
            bd.setBatch_course(CourseDao.getCourseId(awtCourse.getSelectedItem().toString()));
            
            bd.setBatch_faculty(EmployeeDao.getEmployeeId(awtFaculty.getSelectedItem().toString()));
            big.setFaculty(awtFaculty.getSelectedItem().toString());
            big.setCourse(awtCourse.getSelectedItem().toString());

            //bd.setBatch_name(txtBatchName.getText());
            SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yy");
            String x="";
            if(pm.isSelected())
                x="PM";
            else
                x="AM";
            big.setTime(hh.getSelectedItem().toString(),mm.getSelectedItem().toString(),x);
            big.setDate(awtStartDate.getDate());
            big.setDays(days);
            String start=sdf.format(awtStartDate.getDate());
            bd.setBatch_start_date(start);
            bd.setBatch_timming(hh.getSelectedItem().toString()+":"+mm.getSelectedItem().toString()+x);

            //bd.setSession_id(awtSessionId.getSelectedItem());
            bd.setBatch_id(big.getId().toString());
            bd.setBatch_days(days);
            System.out.println(big.getId());
            BatchDao.addBatch(bd);
        } catch (SQLException ex) {
             if(ex.getMessage().contains("Duplicate entry")){
                             JOptionPane.showMessageDialog(null,"Batch Already Present","Error",JOptionPane.ERROR_MESSAGE);
       
                             return;
                         }
              JOptionPane.showMessageDialog(null,"Something went wrong try again later!","Error",JOptionPane.ERROR_MESSAGE);
         return;
        }
        JOptionPane.showMessageDialog(null,"Batch Added successfully","Done",JOptionPane.INFORMATION_MESSAGE);
        
        awtStartDate.setDate(null);
        awtCourse.requestFocus();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        JOptionPane.showMessageDialog(null,"printing");
    }//GEN-LAST:event_jButton1KeyPressed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
//        this.setVisible(false);
//        new MainFrame().setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyReleased

    private void awtCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_awtCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_awtCourseActionPerformed

    private void awtStartDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_awtStartDateMouseClicked
        // TODO add your handling code here:
        //          SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yy");
        //            String start=sdf.format(awtStartDate.getDate());
        //        try {
            //            list=MyPayementDao.getMyPayementDetailsDateWise(1, start);
            //            showDataInTable();
            //        } catch (SQLException ex) {
            //            Logger.getLogger(ViewDayWiseFeeCollectionByCashier.class.getName()).log(Level.SEVERE, null, ex);
            //        }

    }//GEN-LAST:event_awtStartDateMouseClicked

    private void awtStartDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_awtStartDateKeyPressed
        // TODO add your handling code here:
        //          if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            //               SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yy");
            //            String start=sdf.format(awtStartDate.getDate());
            //        try {
                //            list=MyPayementDao.getMyPayementDetailsDateWise(1, start);
                //            showDataInTable();
                //        } catch (SQLException ex) {
                //            Logger.getLogger(ViewDayWiseFeeCollectionByCashier.class.getName()).log(Level.SEVERE, null, ex);
                //        }
            //          }
    }//GEN-LAST:event_awtStartDateKeyPressed

    private void awtFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_awtFacultyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_awtFacultyActionPerformed

    private void awtFacultyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_awtFacultyKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_awtFacultyKeyPressed

    private void awtCenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_awtCenterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_awtCenterActionPerformed

    private void awtCenterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_awtCenterKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_awtCenterKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         new Login().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
         ProfilesSelector mf=new ProfilesSelector(ed);
            mf.setVisible(true);
            this.dispose(); 
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBatchNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBatchNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBatchNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBatchNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                WebLookAndFeel.install();
                new AddBatchNew().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JRadioButton am;
    private javax.swing.JComboBox awtCenter;
    private javax.swing.JComboBox awtCourse;
    private javax.swing.JComboBox awtFaculty;
    private com.toedter.calendar.JDateChooser awtStartDate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel employeeName;
    private javax.swing.JCheckBox friday;
    private javax.swing.JComboBox hh;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JComboBox mm;
    private javax.swing.JCheckBox monday;
    private javax.swing.JRadioButton pm;
    private javax.swing.JCheckBox saturday;
    private javax.swing.JCheckBox sunday;
    private javax.swing.JCheckBox thursday;
    private javax.swing.JCheckBox tuesday;
    private javax.swing.JCheckBox wednesday;
    // End of variables declaration//GEN-END:variables
}
