/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scaapp.gui;

import scaapp.pojo.EmployeeDetails;
import com.alee.laf.WebLookAndFeel;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import scaapp.dao.BatchDao;
import scaapp.dao.CenterDao;

import scaapp.dao.EmployeeDao;
import scaapp.pojo.BatchDetailsDisplay;
import scaapp.pojo.ShowBatch;
import scaapp.utils.DBConnection;
import scaapp.utils.InternetUtil;

/**
 *
 * @author Comp10
 */
public class BatchStatus extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    ImageIcon icon = new ImageIcon("src\\resources\\loading.gif");
    final JOptionPane optionPane = new JOptionPane( "Loading.....", JOptionPane.NO_OPTION, JOptionPane.NO_OPTION,icon, new Object[]{}, icon);
    final JDialog dialog = new JDialog();
    EmployeeDetails ed;
     ArrayList<ShowBatch> batchList=null;
    public BatchStatus() {
        initComponents();
        setLocationRelativeTo(null);
        System.out.println(new File("src/resources/").listFiles().length);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
        dialog.setContentPane(optionPane);
       
        dialog.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        dialog.pack();
       
    }

    BatchStatus(EmployeeDetails ed) {
       this();
       this.ed=ed;
         
       batchList=new ArrayList();
        try {
            batchList = BatchDao.getAllBatches(ed.getCentre_id());
        } catch (SQLException ex) {
            Logger.getLogger(PendingFeeDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
         for(ShowBatch s:batchList)
               batches.addItem(s.getBatchid());
       
    }

    public void applyFilter(){
         if(awtStartDate.getDate()==null){
            JOptionPane.showMessageDialog(null,"Please Select date","Error",JOptionPane.INFORMATION_MESSAGE);
            return;
        
        }   
          if(awtEndDate.getDate()==null){
            JOptionPane.showMessageDialog(null,"Please Select date","Error",JOptionPane.INFORMATION_MESSAGE);
            return;
        
        }   
          
          
          batches.removeAllItems(); 
          SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yy");
       Date date=null;
          
          for(ShowBatch sb:batchList){
      
             try {
                 date=sdf.parse(sb.getStart());
             } catch (ParseException ex) {
                 Logger.getLogger(BatchStatus.class.getName()).log(Level.SEVERE, null, ex);
             }
             if((date.after(awtStartDate.getDate())||date.equals(awtStartDate.getDate()))&&(date.before(awtEndDate.getDate())||date.equals(awtEndDate.getDate())))
                 batches.addItem(sb.getBatchid());
          }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        mansarovar = new javax.swing.JCheckBox();
        indrapuri = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtcourseName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtBatchDays = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtBatchTime = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        batches = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jtBatchFaculty = new javax.swing.JTextField();
        active = new javax.swing.JCheckBox();
        lockVisual = new javax.swing.JLabel();
        awtStartDate = new com.toedter.calendar.JDateChooser();
        awtEndDate = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        mansarovar.setText("Mansarovar");
        mansarovar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mansarovarActionPerformed(evt);
            }
        });

        indrapuri.setText("Indrapuri");

        jLabel14.setText("Start Date");

        jLabel13.setText("End Date");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ChangeBatchStatus - SCAOnCloud v1.0.0");
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Batch details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jLabel2.setText("Course");

        jtcourseName.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtcourseName.setEnabled(false);

        jLabel3.setText("Days");

        jtBatchDays.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtBatchDays.setEnabled(false);

        jLabel4.setText("Time");

        jtBatchTime.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtBatchTime.setEnabled(false);

        jLabel9.setText("Batch code");

        batches.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                batchesItemStateChanged(evt);
            }
        });
        batches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchesActionPerformed(evt);
            }
        });
        batches.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                batchesKeyPressed(evt);
            }
        });

        jLabel10.setText("Faculty");

        jtBatchFaculty.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtBatchFaculty.setEnabled(false);

        active.setText("Active");
        active.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activeActionPerformed(evt);
            }
        });

        lockVisual.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lockVisual.setForeground(new java.awt.Color(255, 51, 51));

        jLabel15.setText("Start Date");

        jLabel16.setText("End Date");

        jButton1.setText("Filter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(active, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtcourseName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(jtBatchDays, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtBatchTime, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtBatchFaculty)
                                    .addComponent(batches, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(lockVisual, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(6, 6, 6))
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(awtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(awtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 85, Short.MAX_VALUE))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(awtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(awtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtcourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtBatchDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtBatchTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtBatchFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(batches, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(active)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lockVisual, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton9.setText("Back");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton8.setText("Logout");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton8)
                        .addGap(7, 7, 7))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton8))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void batchesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_batchesItemStateChanged
        try {
            // TODO add your handling code here:
if(batches.getSelectedItem()==null)
   return;
            BatchDetailsDisplay bdd=BatchDao.showRecord(batches.getSelectedItem().toString());

            jtcourseName.setText(bdd.getCourseName());
            jtBatchDays.setText(bdd.getBatchDays());
            jtBatchTime.setText(bdd.getBatchTime());
            jtBatchFaculty.setText(bdd.getFacultyName());
            if(bdd.getActive()==1)
                active.setSelected(true);
            else
                active.setSelected(false);

            System.out.println(bdd);
        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(null,"Something went wrong try again later!","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }

    }//GEN-LAST:event_batchesItemStateChanged

    private void batchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_batchesActionPerformed

    private void batchesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_batchesKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){

          //  register();

            //jButton1.requestFocus();

        }

    }//GEN-LAST:event_batchesKeyPressed

    private void activeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activeActionPerformed
       
         if(awtStartDate.getDate()==null){
            JOptionPane.showMessageDialog(null,"Please Select date","Error",JOptionPane.INFORMATION_MESSAGE);
            return;
        
        }   
          if(awtEndDate.getDate()==null){
            JOptionPane.showMessageDialog(null,"Please Select date","Error",JOptionPane.INFORMATION_MESSAGE);
            return;
        
        }   
          
         SimpleDateFormat sdf=new SimpleDateFormat("yy-MM-dd");
           String start=sdf.format(awtStartDate.getDate());
           String end=sdf.format(awtEndDate.getDate());
        System.out.println(start);
        System.out.println(end);
       // getData(start,end);
        
        
        try {
            // TODO add your handling code here:
              dialog.setLocationRelativeTo(this);
              dialog.setVisible(true);
              this.setEnabled(false);
            int code=0;
            if(active.isSelected())
            {
                code=1;
            }
            else
            {
                code=0;
            }
            BatchDao.changeActiveStatus(batches.getSelectedItem().toString(), code);
            
            // studentId.requestFocus();
        } catch (SQLException ex) {
            dialog.dispose();
               this.setEnabled(true);
            JOptionPane.showMessageDialog(null,"Something went wrong try again later!","Error",JOptionPane.ERROR_MESSAGE);
                  return;
        }
         dialog.dispose();
               this.setEnabled(true);
        JOptionPane.showMessageDialog(null,"Updated","Done",JOptionPane.INFORMATION_MESSAGE);
                  
    }//GEN-LAST:event_activeActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        ProfilesSelector mf=new ProfilesSelector(ed);
        mf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void mansarovarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mansarovarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_mansarovarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        applyFilter();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BatchStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BatchStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BatchStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BatchStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                WebLookAndFeel.install();
                new BatchStatus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox active;
    private com.toedter.calendar.JDateChooser awtEndDate;
    private com.toedter.calendar.JDateChooser awtStartDate;
    private javax.swing.JComboBox batches;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox indrapuri;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jtBatchDays;
    private javax.swing.JTextField jtBatchFaculty;
    private javax.swing.JTextField jtBatchTime;
    private javax.swing.JTextField jtcourseName;
    private javax.swing.JLabel lockVisual;
    private javax.swing.JCheckBox mansarovar;
    // End of variables declaration//GEN-END:variables


}
