/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scaapp.gui;

import scaapp.pojo.EmployeeDetails;
import com.alee.laf.WebLookAndFeel;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import scaapp.dao.CenterDao;

import scaapp.dao.EmployeeDao;
import scaapp.utils.DBConnection;
import scaapp.utils.InternetUtil;
import scaapp.utils.SMSSender;

/**
 *
 * @author Comp10
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    ImageIcon icon = new ImageIcon("src\\resources\\loading.gif");
    final JOptionPane optionPane = new JOptionPane("Loading.....", JOptionPane.NO_OPTION, JOptionPane.NO_OPTION, icon, new Object[]{}, icon);
    final JDialog dialog = new JDialog();

    public Login() {
        initComponents();
        
        
        setLocationRelativeTo(null);
        System.out.println(new File("src/resources/").listFiles().length);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
        dialog.setContentPane(optionPane);

        dialog.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        dialog.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        userId = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        indrapuri = new javax.swing.JRadioButton();
        mansarovar = new javax.swing.JRadioButton();
        password = new javax.swing.JPasswordField();
        batchType = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login - SCAOnCloud v1.0.0");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        userId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userIdKeyPressed(evt);
            }
        });

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Contact number");

        jLabel2.setText("Password");

        buttonGroup1.add(indrapuri);
        indrapuri.setText("Indrapuri");
        indrapuri.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                indrapuriKeyPressed(evt);
            }
        });

        buttonGroup1.add(mansarovar);
        mansarovar.setSelected(true);
        mansarovar.setText("Mansarovar");
        mansarovar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mansarovarActionPerformed(evt);
            }
        });
        mansarovar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mansarovarKeyPressed(evt);
            }
        });

        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordKeyPressed(evt);
            }
        });

        batchType.setText("Login For project batches");
        batchType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchTypeActionPerformed(evt);
            }
        });

        jButton2.setText("View Fees");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Enquiry");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(batchType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(mansarovar)
                        .addGap(18, 18, 18)
                        .addComponent(indrapuri))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(82, 82, 82)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userId)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3))
                            .addComponent(password))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(indrapuri)
                    .addComponent(mansarovar)
                    .addComponent(batchType))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userIdKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int result = validateData();
            if (result == 1) {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(null, "Phone Number must be in the form XXXXXXXXXX");
                //userId.setText("");
                userId.requestFocus();
                return;
            }
            password.requestFocus();
        }
    }//GEN-LAST:event_userIdKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

//        if(batchType.isSelected()){
//           DBConnection.setBatchType("PROJECT");
//           
//        
//        }
//        else
//            DBConnection.setBatchType("NORMAL");
        if (!InternetUtil.check()) {
            JOptionPane.showMessageDialog(null, "Please check your Internet Connection", "NO INTERNET", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int result = validateData();
        if (result == 0) {
            login();
        } else if (result == 1) {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, "Phone Number must be in the form XXXXXXXXXX");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int result = validateData();
            if (result == 1) {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(null, "Phone Number must be in the form XXXXXXXXXX");
                //userId.setText("");
                userId.requestFocus();
                return;
            }
            mansarovar.requestFocus();
        }
    }//GEN-LAST:event_passwordKeyPressed

    private void mansarovarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mansarovarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int result = validateData();
            if (result == 1) {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(null, "Phone Number must be in the form XXXXXXXXXX");
                //userId.setText("");
                userId.requestFocus();
                return;
            }
            login();
        }
    }//GEN-LAST:event_mansarovarKeyPressed

    private void indrapuriKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_indrapuriKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int result = validateData();
            if (result == 1) {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(null, "Phone Number must be in the form XXXXXXXXXX");
                //userId.setText("");
                userId.requestFocus();
                return;
            }
            if (!InternetUtil.check()) {
                JOptionPane.showMessageDialog(null, "Please check your Internet Connection", "NO INTERNET", JOptionPane.ERROR_MESSAGE);
                return;
            }
            login();
        }
    }//GEN-LAST:event_indrapuriKeyPressed

    private void batchTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchTypeActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_batchTypeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ViewFeesTable mf = new ViewFeesTable();
        mf.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void mansarovarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mansarovarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mansarovarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         EnquiryHandler mf = new EnquiryHandler();
        mf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                WebLookAndFeel.install();
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox batchType;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton indrapuri;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton mansarovar;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField userId;
    // End of variables declaration//GEN-END:variables

    public void login() {
        //load();
        Runnable r = () -> {
            dialog.setLocationRelativeTo(Login.this);
            dialog.setVisible(true);
            this.setEnabled(false);

            try {
                if (batchType.isSelected()) {
                    DBConnection.setBatchType("PROJECT");

                } else {
                    SMSSender.main(null);
                    DBConnection.setBatchType("NORMAL");
                }

                System.out.println("on 311");
                // TODO add your handling code here:
                EmployeeDetails ed = EmployeeDao.validateEmployee(userId.getText(), String.valueOf(password.getPassword()));
                System.out.println("on 313");
                if (ed != null) {
                    if (mansarovar.isSelected()) {
                        ed.setCentre_id(CenterDao.getCenterId(mansarovar.getText()));
                    } else {
                        ed.setCentre_id(CenterDao.getCenterId(indrapuri.getText()));
                    }
                    System.out.println("Center is " + ed.getCentre_id());
                    System.out.println(String.valueOf(password.getPassword()));
                    if (batchType.isSelected()) {
                        ed.setBatchType("PROJECT");
                    } else {
                        ed.setBatchType("NORMAL");
                    }

                    JOptionPane.showMessageDialog(null, "Login Accepted!! \nWelcome " + ed.getEmp_name());
                    // load();
                    if (EmployeeDao.CheckPermission(ed)) {
                        System.out.println("Hello from cp");
                        ProfilesSelector mf = new ProfilesSelector(ed);
                        mf.setVisible(true);
                        this.dispose();
                    } else {
                        MainFrame mf = new MainFrame(ed);
                        mf.setVisible(true);
                        this.dispose();
                    }
                } else {
                    dialog.dispose();
                    this.setEnabled(true);

                    JOptionPane.showMessageDialog(null, "Login Denied wrong username/password");
                    //  load();
                    password.setText("");
                    password.requestFocus();
                }

            } catch (SQLException ex) {
                //Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                ex.printStackTrace();
                dialog.dispose();
                this.setEnabled(true);
                JOptionPane.showMessageDialog(null, "Something went wrong try again later!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            } catch (Exception ex) {
                ex.printStackTrace();
                dialog.dispose();
                this.setEnabled(true);
                //Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Something went wrong try again later!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            dialog.dispose();
            this.setEnabled(true);
        };
        Thread th = new Thread(r);
        th.start();
    }

    public int validateData() {
        Pattern pattern = Pattern.compile("^[6-9]\\d{9}$");
        Matcher matcher = pattern.matcher(userId.getText());
        if (!matcher.matches()) {
            return 1;
        } else {
            return 0;
        }
    }

//     public void load(){
//        if(loading.isVisible())
//            loading.setVisible(false);
//        else
//            loading.setVisible(true);
//    }
}
