/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scaapp.gui;

import scaapp.pojo.EmployeeDetails;
import com.alee.laf.WebLookAndFeel;
import java.awt.AWTKeyStroke;

//import com.alee.laf.WebLookAndFeel;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.AbstractAction;
import javax.swing.ImageIcon;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import scaapp.dao.BatchDao;
import scaapp.dao.CourseDao;
import scaapp.dao.RegistrationDao;
import scaapp.dao.StudentDetailDao;
import scaapp.dao.StudentTransactionDao;
import scaapp.pojo.BatchDetailsDisplay;
import scaapp.pojo.StudentDetail;
import scaapp.pojo.StudentTransaction;
import scaapp.utils.GSTReceiptPrinter;
import scaapp.utils.GSTReceiptPrinterProjectBatch;
import scaapp.utils.OldBatchDetector;

/**
 *
 * @author Comp10
 */
public class MainFrame extends javax.swing.JFrame {
    /**
     * Creates new form MainFrame
     */
    int count=0;
    int EmployeeId=1;
    EmployeeDetails ed;
    StudentDetail sd;
     Date d=null;
    boolean first=true;
     ImageIcon icon = new ImageIcon("src\\resources\\loading.gif");
    final JOptionPane optionPane = new JOptionPane( "Loading.....", JOptionPane.NO_OPTION, JOptionPane.NO_OPTION,icon, new Object[]{}, icon);
    final JDialog dialog = new JDialog();
  @Override
   public void setVisible(boolean val){
       if(ed==null){
        
            JOptionPane.showMessageDialog(null,"Please Login First");
            Login lp=new Login();
            lp.setVisible(true);
            this.dispose();
            //return;
       
          
       }
     
       else{
           super.setVisible(val);
       }
       
   }
    public MainFrame() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
        setLocationRelativeTo(null);
        enterfee.setEnabled(false);
        batches.setEnabled(false);
        jButton1.setEnabled(false);
         JPanel panel = (JPanel) this.getContentPane();
        InputMap im = panel.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        im.put(KeyStroke.getKeyStroke("alt pressed N"), "cN");
        panel.getActionMap().put("cN", new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
               new StudentDetailsNew(ed).setVisible(true);
        MainFrame.this.dispose();  
            }
        });
         im.put(KeyStroke.getKeyStroke("alt pressed C"), "ac");
        panel.getActionMap().put("ac", new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
             startSet();
            }
        });
         im.put(KeyStroke.getKeyStroke("alt pressed q"), "aq");
        panel.getActionMap().put("aq", new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                new TakeFeeDirectly(ed).setVisible(true);
        MainFrame.this.dispose();  
            }
        });
        dialog.setContentPane(optionPane);
       
        dialog.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        dialog.pack();
//        jMenuBar1.add(Box.createHorizontalGlue());
//        JMenu logout = new JMenu();
//        logout.setText("Logout");
//        jMenuBar1.add(logout);
       
       Thread dateThread=new Thread(()->{
         
          d=StudentTransactionDao.getDate();
           
       }
       );
       dateThread.start();
        
        
        
        
    }
    public MainFrame(EmployeeDetails ed){
        this();
        this.ed=ed;
        employeeName.setText(ed.getEmp_name());
    }
    
    public void showEnrollNewStudentFrame(){
        new EnrollNewStudent(ed).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        studentId = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtcourseName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtBatchDays = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtBatchTime = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        batches = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jtBatchFaculty = new javax.swing.JTextField();
        old = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        studentName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        studentEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        studentCollage = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        studentSem = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        studentContact = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        paidFee = new javax.swing.JTextField();
        enterfee = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        dueFee = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        totalFee = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        employeeName = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fee collection - SCAOnCloud v1.0.0");
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Contact details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jLabel1.setText("Contact number/Barcode");

        studentId.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        studentId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIdActionPerformed(evt);
            }
        });
        studentId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                studentIdKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(studentId, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(studentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Batch details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jLabel2.setText("Course");

        jtcourseName.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtcourseName.setEnabled(false);

        jLabel3.setText("Days");

        jtBatchDays.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtBatchDays.setEnabled(false);

        jLabel4.setText("Time");

        jtBatchTime.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtBatchTime.setEnabled(false);

        jLabel9.setText("Batch code");

        batches.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                batchesItemStateChanged(evt);
            }
        });
        batches.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                batchesMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                batchesMousePressed(evt);
            }
        });
        batches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchesActionPerformed(evt);
            }
        });
        batches.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                batchesKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                batchesKeyReleased(evt);
            }
        });

        jLabel10.setText("Faculty");

        jtBatchFaculty.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtBatchFaculty.setEnabled(false);

        old.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        old.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(old, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtcourseName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtBatchDays, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtBatchTime, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(batches, 0, 250, Short.MAX_VALUE)
                            .addComponent(jtBatchFaculty))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(batches, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtcourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtBatchDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtBatchTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtBatchFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(old, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Student Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jLabel5.setText("Name");

        studentName.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        studentName.setEnabled(false);

        jLabel6.setText("Email");

        studentEmail.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        studentEmail.setEnabled(false);

        jLabel7.setText("Semester");

        studentCollage.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        studentCollage.setEnabled(false);

        jLabel8.setText("College");

        studentSem.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        studentSem.setEnabled(false);

        jLabel11.setText("Contact number");

        studentContact.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        studentContact.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(studentEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(studentName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(studentCollage)
                    .addComponent(studentSem)
                    .addComponent(studentContact))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(studentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(studentEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(studentContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(studentCollage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(studentSem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Confirm");
        jButton1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton1FocusGained(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Fee details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        paidFee.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        paidFee.setForeground(new java.awt.Color(51, 153, 0));
        paidFee.setDisabledTextColor(new java.awt.Color(51, 153, 0));
        paidFee.setEnabled(false);

        enterfee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                enterfeeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                enterfeeKeyReleased(evt);
            }
        });

        jLabel14.setText("Fee due");

        dueFee.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        dueFee.setForeground(new java.awt.Color(255, 51, 51));
        dueFee.setDisabledTextColor(new java.awt.Color(255, 51, 51));
        dueFee.setEnabled(false);

        jLabel13.setText("Fee paid");

        jLabel12.setText("Amount");

        jLabel15.setText("Total fees");

        totalFee.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        totalFee.setForeground(new java.awt.Color(0, 102, 102));
        totalFee.setDisabledTextColor(new java.awt.Color(0, 102, 102));
        totalFee.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                        .addComponent(totalFee, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dueFee, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(paidFee, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(enterfee, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(enterfee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(paidFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(dueFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addContainerGap())
        );

        jButton2.setText("Reset");
        jButton2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton2FocusGained(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "User details"));

        jLabel16.setText("You are logged in as ");

        employeeName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        employeeName.setForeground(new java.awt.Color(0, 153, 51));
        employeeName.setText("Anonymous");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(employeeName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(employeeName))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/plus.png"))); // NOI18N
        jMenu1.setText("New");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/user.png"))); // NOI18N
        jMenuItem6.setText("Enroll student");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/plus.png"))); // NOI18N
        jMenuItem10.setText("Add new student");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/rupee.png"))); // NOI18N
        jMenu2.setText("Fee");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/give-money.png"))); // NOI18N
        jMenuItem7.setText("Collect fees");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/time-left.png"))); // NOI18N
        jMenuItem9.setText("Pending fees");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/print.png"))); // NOI18N
        jMenu3.setText("Print");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/id-card.png"))); // NOI18N
        jMenuItem1.setText("ID card");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/id-card.png"))); // NOI18N
        jMenuItem8.setText("Print Id Of Full Batch");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/id-card.png"))); // NOI18N
        jMenuItem12.setText("Duplicate Reciept");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem12);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/eye-open.png"))); // NOI18N
        jMenu4.setText("View");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/user.png"))); // NOI18N
        jMenuItem4.setText("Student details");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/document.png"))); // NOI18N
        jMenuItem5.setText("Daily Collection");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuItem13.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/document.png"))); // NOI18N
        jMenuItem13.setText("Take Attendance");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem13);

        jMenuItem14.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/document.png"))); // NOI18N
        jMenuItem14.setText("View Attendance");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem14);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/lock.png"))); // NOI18N
        jMenu5.setText("Private");

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logout.png"))); // NOI18N
        jMenuItem11.setText("Logout");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem11);

        jMenuItem15.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/reload.png"))); // NOI18N
        jMenuItem15.setText("Change password");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem15);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton2)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
             
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        
    }//GEN-LAST:event_formKeyReleased

    private void studentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentIdActionPerformed

    private void studentIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentIdKeyPressed
        
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
             //load();
              dialog.setLocationRelativeTo(MainFrame.this);
              dialog.setVisible(true);
              this.setEnabled(false);
              
            if(!(validateStudentId(studentId)))
             // if(!(studentId.getText().length()==10||studentId.getText().length()==12))
            {
                dialog.dispose();
               this.setEnabled(true);
                JOptionPane.showMessageDialog(null,"Enter Valid Phone Number or barcode");
                studentId.setText("");
                //JOptionPane.showMessageDialog(null,"Student have not filled form Yet!!");
                studentId.requestFocus();
               
                return;
            }
             try {
            sd=StudentDetailDao.getStudentDetailsByContactNo(studentId.getText().substring(0,10));
            if(sd==null)
            {
                  dialog.dispose();
               this.setEnabled(true);
                studentId.setText("");
                JOptionPane.showMessageDialog(null,"Student has not provided his basic details");
                studentId.requestFocus();
                
                return;
            }
              System.out.println("Enter called");
 ArrayList <String> batchesList=null;
        try {
            batchesList=RegistrationDao.getAllBatchIdOfSingleStudent(studentId.getText().substring(0,10));
        } catch (SQLException ex) {
              dialog.dispose();
               this.setEnabled(true);
             JOptionPane.showMessageDialog(null,"Something went wrong try again later!","Error",JOptionPane.ERROR_MESSAGE);
             return;
        }
        if(batchesList.size()==0)
             {
                 dialog.dispose();
               this.setEnabled(true);
                studentId.setText("");
                JOptionPane.showMessageDialog(null,"Student is not enrolled in any batch. Please enroll student in batch first!");
                studentId.requestFocus();
                  
                return;
            }
               studentId.setEnabled(false);
                
               //sd=StudentDetailDao.getStudentDetailsByContactNo(studentId.getText().substring(0,10));
                 System.out.println("Name is "+sd.getStudentName());
                  studentName.setText(sd.getStudentName().toUpperCase());
                  
               sd.setStudentContact(studentId.getText().substring(0,10));
              
               studentContact.setText(sd.getStudentContact());
               studentEmail.setText(sd.getStudentEmail().toUpperCase());
               studentCollage.setText(sd.getStudentCollege().toUpperCase());
               studentSem.setText(sd.getStudentSem());
               
                 System.out.println("801");
         for(String s: batchesList)
          batches.addItem(s);
         if(batchesList.size()>1){
              jButton1.setEnabled(true);                                      
        dialog.dispose();
               this.setEnabled(true);
             batches.setEnabled(true);
              batches.requestFocus();
            batches.showPopup();
            
         }
         else{
                 
                 setPaidFee();
                 setTotalFee();
                 setDueFee();
                 if(isFeeComplete()){
            
                batches.setEnabled(false);
                JOptionPane.showMessageDialog(null, "Fee has been completed for this batch ");
                
              //batches.requestFocus();
            batches.hidePopup();
              dialog.dispose();
               this.setEnabled(true);
            
               startSet();
                paidFee.setText("");
               dueFee.setText("");
               totalFee.setText("");
               return;
               
           }
                System.out.println("on line 861");
                 jButton1.setEnabled(true); 
                  dialog.dispose();
               this.setEnabled(true);
                enterfee.setEnabled(true);
                 enterfee.requestFocus();
                 return;
                 }      
               
               System.out.println(sd);
            } catch (SQLException ex) {
                dialog.dispose();
               this.setEnabled(true);
                 JOptionPane.showMessageDialog(null,"Something went wrong try again later!","Error",JOptionPane.ERROR_MESSAGE);
            }
             //load();
         }
      
    }//GEN-LAST:event_studentIdKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       //this.setEnabled(false);
        pay();
        //this.setEnabled(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        //JOptionPane.showMessageDialog(null,"printing");
       
    }//GEN-LAST:event_jButton1KeyPressed

    private void batchesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_batchesKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
           enterfee.setEnabled(true);
           enterfee.requestFocus(true);
           batches.hidePopup();
          // batches.setEnabled(false);
           setPaidFee();
           setTotalFee();
           setDueFee();
           if(isFeeComplete()){
               JOptionPane.showMessageDialog(null,"Fee is completed for this batch for this student!!");
               paidFee.setText("");
               dueFee.setText("");
               totalFee.setText("");
               enterfee.setEnabled(false);
               // batches.showPopup();
               batches.requestFocus();
                batches.showPopup();
               return;
               
           }
           
           //batches.showPopup();
        }
    }//GEN-LAST:event_batchesKeyPressed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new GenerateIDCard(ed).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void batchesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_batchesItemStateChanged
        // TODO add your handling code here:
        if(batches.getSelectedItem()==null)
            return;
            try {
            // TODO add your handling code here:
            BatchDetailsDisplay bdd=BatchDao.showRecord(batches.getSelectedItem().toString());
            
           jtcourseName.setText(bdd.getCourseName());
            jtBatchDays.setText(bdd.getBatchDays());
            jtBatchTime.setText(bdd.getBatchTime());
            jtBatchFaculty.setText(bdd.getFacultyName());
                System.out.println(d);
            if(d==null)
                 System.exit(0);
                boolean isOld=false;
            try {
                isOld=OldBatchDetector.isOld(bdd.getStartingDate(),d);
            } catch (ParseException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(isOld)
            old.setText("Old Student");
            else
            old.setText("");    
//             enterfee.setEnabled(true);
//           enterfee.requestFocus(true);
//           batches.hidePopup();
           //batches.setEnabled(false);
           setPaidFee();
           setTotalFee();
           setDueFee();
           
           if(isFeeComplete()){
             
               enterfee.setEnabled(false);
               // batches.showPopup();
               batches.requestFocus();
                batches.showPopup();
               return;
               
           }
           enterfee.setEnabled(true);
            System.out.println(bdd);
        } catch (SQLException ex) {
              JOptionPane.showMessageDialog(null,"Something went wrong try again later!","Error",JOptionPane.ERROR_MESSAGE);
        
        }
    }//GEN-LAST:event_batchesItemStateChanged

    private void batchesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_batchesKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_batchesKeyReleased

    private void enterfeeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enterfeeKeyPressed
         
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        //this.setEnabled(false);
        pay();
        //this.setEnabled(true);
         }
    }//GEN-LAST:event_enterfeeKeyPressed

    private void enterfeeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enterfeeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_enterfeeKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        startSet();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
         new MainFrame(ed).setVisible(true);
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
         new ViewStudentDetails(ed).setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        new ViewDayWiseFeeCollectionByCashier(ed).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
       new MainFrame(ed).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
         new PendingFeeDetails(ed).setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
         new Login().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        new GenerateIDCardOfFullBatch(ed).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void batchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchesActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_batchesActionPerformed

    private void batchesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_batchesMouseClicked
        // TODO add your handling code here:
          
    }//GEN-LAST:event_batchesMouseClicked

    private void batchesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_batchesMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_batchesMousePressed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        System.out.println("Hello");
        new TakeStudentAttendance(ed).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        
        new ViewAttendance(ed).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
        new ChangePassword(ed).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jButton2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton2FocusGained
        enterfee.requestFocus();
    }//GEN-LAST:event_jButton2FocusGained

    private void jButton1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton1FocusGained
        enterfee.requestFocus();
    }//GEN-LAST:event_jButton1FocusGained

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        new GenerateDuplicateReciept(ed).setVisible(true);
          this.dispose();
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        new StudentDetailsNew(ed).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        new EnrollNewStudent(ed).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                WebLookAndFeel.install ();
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox batches;
    private javax.swing.JTextField dueFee;
    private javax.swing.JLabel employeeName;
    private javax.swing.JTextField enterfee;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jtBatchDays;
    private javax.swing.JTextField jtBatchFaculty;
    private javax.swing.JTextField jtBatchTime;
    private javax.swing.JTextField jtcourseName;
    private javax.swing.JLabel old;
    private javax.swing.JTextField paidFee;
    private javax.swing.JTextField studentCollage;
    private javax.swing.JTextField studentContact;
    private javax.swing.JTextField studentEmail;
    private javax.swing.JTextField studentId;
    private javax.swing.JTextField studentName;
    private javax.swing.JTextField studentSem;
    private javax.swing.JTextField totalFee;
    // End of variables declaration//GEN-END:variables

private void setPaidFee(){
        try {
            paidFee.setText(StudentTransactionDao.getStudentTotalPaidFeeInSingleBatch(studentId.getText().substring(0,10), batches.getSelectedItem().toString())+"");
            //JOptionPane.showMessageDialog(null, "all done");
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
}
        public void startSet(){
     sd=null;
        studentName.setText("");
        studentContact.setText("");
        studentEmail.setText("");
        studentCollage.setText("");
        studentSem.setText("");
        enterfee.setText("");
        studentId.setText("");
        jtcourseName.setText("");
        jtBatchDays.setText("");
        jtBatchTime.setText("");
        jtBatchFaculty.setText("");
        paidFee.setText("");
        dueFee.setText("");
        totalFee.setText("");
        batches.removeAllItems();
        batches.setEnabled(false);
        enterfee.setEnabled(false);
        studentId.setEnabled(true);
        studentId.requestFocus(true);
        jButton1.setEnabled(false);
        old.setText("");
}
private void setTotalFee(){
        try {
            totalFee.setText(CourseDao.getCourseFeeByBatchId(batches.getSelectedItem().toString())+"");
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
}
private void setDueFee(){
       double due=Double.parseDouble(totalFee.getText())-Double.parseDouble(paidFee.getText());
       dueFee.setText(due+"");
}
private boolean isFeeComplete(){
    System.out.println("In fee complete"+Double.parseDouble(totalFee.getText()));
     System.out.println("In fee complete"+Double.parseDouble(paidFee.getText()));
   if(Double.parseDouble(totalFee.getText())==Double.parseDouble(paidFee.getText()))
             {
                 System.out.println("In fee complete in if");
                  batches.setEnabled(true);
              batches.requestFocus();
            batches.showPopup();
            return true;
             }
   return false;
}
 private void pay(){
//               if(!InternetUtil.check())
//    {
//         JOptionPane.showMessageDialog(null,"Please check your Internet Connection","NO INTERNET",JOptionPane.ERROR_MESSAGE);
//         return;
//    }
               Runnable r1=()->{dialog.setVisible(true);
      this.setEnabled(false);
        
      try{
     if(Double.parseDouble(enterfee.getText())<=0)  {
                    dialog.dispose();
                 JOptionPane.showMessageDialog(null,"Please enter vailid amount!");
                 enterfee.setText("");
                 this.setEnabled(true);
                 enterfee.requestFocus();
                  
                 
                 return;
             }
     if((Double.parseDouble(enterfee.getText())%100)!=0)  {
         dialog.dispose();
                 JOptionPane.showMessageDialog(null,"Amount should be entered in multiples of 100");
                 enterfee.setText("");
                 this.setEnabled(true);
                 enterfee.requestFocus();
                 
                 return;
             }
      if(Double.parseDouble(dueFee.getText())<Double.parseDouble(enterfee.getText()))
             {
                 dialog.dispose();
                 JOptionPane.showMessageDialog(null,"Amount Due is Rs."+dueFee.getText());
                 enterfee.setText("");
                 this.setEnabled(true);
                 enterfee.requestFocus();
                
                 return;
             }
      }
      catch(NumberFormatException ex){
          dialog.dispose();
          JOptionPane.showMessageDialog(null,"Enter Valid Amount");
          System.out.println(ex);
                 enterfee.setText("");
                 this.setEnabled(true);
                 enterfee.requestFocus();
                
                 return;
      }
         
               
      String message="Amount- "+enterfee.getText()+"\nbatch-Id-"+batches.getSelectedItem().toString()+"\nStudent Name-  "+studentName.getText();
      
        JOptionPane optionPane = new JOptionPane(message+"\n\nWould you like to confirm Payment?", JOptionPane.QUESTION_MESSAGE, JOptionPane.YES_NO_OPTION);
    JDialog dialog = optionPane.createDialog("Confirm Payment?");
    Set<AWTKeyStroke> focusTraversalKeys = new HashSet<AWTKeyStroke>(dialog.getFocusTraversalKeys(0));
    focusTraversalKeys.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_RIGHT, KeyEvent.VK_UNDEFINED));
    dialog.setFocusTraversalKeys(0, focusTraversalKeys);
    dialog.setVisible(true);
    dialog.dispose();
    
        
    Integer dialogResult = (Integer) optionPane.getValue();
//    if(option==null)
//        System.out.println("nulla");
//    
      
      
      
      
      //int dialogResult = JOptionPane.showConfirmDialog (null, message+"\n\nWould you like to confirm Payement?","Warning",JOptionPane.YES_NO_OPTION);
        if(dialogResult==null || dialogResult == JOptionPane.NO_OPTION || dialogResult == JOptionPane.CLOSED_OPTION){
          // Saving code here
             this.dialog.dispose();
              studentId.setText("");
              studentId.setEnabled(true);
              startSet();
              this.setEnabled(true);
              studentId.requestFocus();
              JOptionPane.showMessageDialog(null,"Transaction Cancelled!!");
              return;
        }
        
//                  if(!InternetUtil.check())
//    {
//        dialog.dispose();
//         JOptionPane.showMessageDialog(null,"Please check your Internet Connection","NO INTERNET",JOptionPane.ERROR_MESSAGE);
//         this.setEnabled(true);
//         return;
//    }
      
      
     
      
                   System.out.println("on 1387 below date"+d);
      Calendar c=Calendar.getInstance();
      c.setTime(d);
       int year;
        int month = c.get(Calendar.MONTH);
          if(month>=3)
              year=c.get(Calendar.YEAR);
          else
              year=c.get(Calendar.YEAR)-1;
          
            
             int amount=Integer.parseInt(enterfee.getText());
             StudentTransaction st=new StudentTransaction();
             st.setEmployeeId(ed.getEmp_id());
             st.setStudentId(sd.getStudentContact());
//            try {
//                st.setTransactionId("MN/"+year+"-"+(year+1)+"/"+StudentTransactionDao.getNewTransactionId(null));
//                
//                 //st.setTransactionId("MN/2018-2019/1008");
//            } catch (SQLException ex) {
//                Logger.getLogger(FeePayment.class.getName()).log(Level.SEVERE, null, ex);
//            }
             st.setPayementModeId(1);
             st.setBatchId(batches.getSelectedItem().toString());
             st.setCentreId(ed.getCentre_id());
             st.setGrossAmount(amount);
             st.setCgstAmount((int)(amount*0.09));
             st.setSgstAmount((int)(amount*0.09));
             st.setNetAmount(amount-(st.getSgstAmount()+st.getCgstAmount()));
              st.setEmail(sd.getStudentEmail());
             SimpleDateFormat sdf=new SimpleDateFormat("yy-MM-dd");
             String date=sdf.format(d);
             st.setDateOfPayement(date);
             
            
//                    if(!InternetUtil.check())
//    {
//        dialog.dispose();
//         this.setEnabled(true);
//         JOptionPane.showMessageDialog(null,"Please check your Internet Connection","NO INTERNET",JOptionPane.ERROR_MESSAGE);
//         return;
//         
//    }
                 
                 
                      try {
                          if(ed.getBatchType().equalsIgnoreCase("project"))
                              st.setTransactionId("A2I/"+year+"-"+(year+1)+"/"+StudentTransactionDao.getNewTransactionId(null));
                           else
                 {
                     if(ed.getCentre_id()==1)
                              st.setTransactionId("SCA/"+year+"-"+(year+1)+"/"+StudentTransactionDao.getNewTransactionIdNew(year,ed.getCentre_id()));
                        //st.setTransactionId("MN/2018-2019/79");
                     else
                     {
                         st.setTransactionId("SCAI/"+year+"-"+(year+1)+"/"+StudentTransactionDao.getNewTransactionIdNew(year,ed.getCentre_id()));
                       
                     }
                              
                              
                 }
                  //st.setTransactionId("MN/"+year+"-"+(year+1)+"/"+"999");
//                 if(!RegistrationDao.isRegistered(st.getStudentId(), st.getBatchId()))
//                 {
//                     RegistrationDao.registerStudentInBatch(st.getStudentId(), st.getBatchId());
//                 }
                StudentTransactionDao.addStudentTransaction(st);
               // new GSTReceiptPrinter().printGstReciept(st,sd.getStudentName());
               
                
                
                
                
                  // 
            } catch (SQLException ex) {
                       if(ex.getMessage().contains("Duplicate entry")){
                             setDueFee();
                         }
             JOptionPane.showMessageDialog(null,"Something went wrong try again later!","Error",JOptionPane.ERROR_MESSAGE);
                  
         this.setEnabled(true);
          this.dialog.dispose();
                       ex.printStackTrace();
               return;
            }
                      
            
            
              String s=sd.getStudentName();
                String emp=ed.getEmp_name();
                Runnable r=null;
                if(ed.getBatchType().equalsIgnoreCase("NORMAL"))
                r=()-> new GSTReceiptPrinter().printGstReciept(st,s,emp);
                else
                r=()-> new GSTReceiptPrinterProjectBatch().printGstReciept(st,s,emp);    
                Thread t=new Thread(r);
                t.start();
                
                //new GSTReceiptPrinter().printGstReciept(st,sd.getStudentName());   dialog.dispose();
                   this.dialog.dispose();
                startSet();
             this.setEnabled(true);
             studentId.requestFocus(true);
             jButton1.setEnabled(false);
               };
               Thread t=new Thread(r1);
                t.start();
             
 }
    public void load(){
//        if(loading.isVisible())
//            loading.setVisible(false);
//        else
//            loading.setVisible(true);
    }
    
    public boolean validateStudentId(JTextField j){
        Pattern pattern1 = Pattern.compile("^[6-9]\\d{9}$");
        Pattern pattern2 = Pattern.compile("^(?=.*0)[0-9]{12}$");
        Matcher matcher1 = pattern1.matcher(j.getText());
        Matcher matcher2 = pattern2.matcher(j.getText());
        System.out.println(matcher1.matches()+" "+matcher2.matches());
        if(matcher1.matches()){
            return true;
        }
        else if(j.getText().length()==12){
            return true;
        }
        else{
            return false;
        }
    }
}
