/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scaapp.gui;

import scaapp.pojo.EmployeeDetails;
import com.alee.laf.WebLookAndFeel;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.table.DefaultTableModel;
import scaapp.pojo.MyPayement;
import scaapp.pojo.StudentTransaction;

/**
 *
 * @author Comp10
 */
public class ReprintReciept extends javax.swing.JFrame {

    /**
     * Creates new form FeeDetailsTable
     */
    ArrayList<StudentTransaction> list;
    private  DefaultTableModel model;
    EmployeeDetails ed;
    public ReprintReciept() {
        initComponents();
        setLocationRelativeTo(null);
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
        //setUndecorated(true);
//getRootPane().setWindowDecorationStyle(JRootPane.NONE);
    }
    public ReprintReciept(ArrayList<StudentTransaction> list) {
       this();
       this.list=list;
       this.model = (DefaultTableModel)jtTransactionDetails.getModel();
       showDataInTable();
        //setUndecorated(true);
//getRootPane().setWindowDecorationStyle(JRootPane.NONE);
    }
    
//    public FeeDetailsTable(){
//        
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtTransactionDetails = new javax.swing.JTable();
        Ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fee details - SCAOnCloud v1.0.0");
        setUndecorated(true);
        setResizable(false);

        jtTransactionDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Transaction id", "Cashier", "Centre", "Gross amount", "Date of payment"
            }
        ));
        jtTransactionDetails.setEnabled(false);
        jtTransactionDetails.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jtTransactionDetails);

        Ok.setText("Ok");
        Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Ok)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ok)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_OkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReprintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReprintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReprintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReprintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                WebLookAndFeel.install();
                new ReprintReciept().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ok;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtTransactionDetails;
    // End of variables declaration//GEN-END:variables

private void showDataInTable()
    {
   
//        try
//        {
//            ArrayList<Performance> performanceList=PerformanceDAO.getAllData();
//            if(performanceList.isEmpty())
//            {
//                JOptionPane.showMessageDialog(null,"Sorrry! No STudent Has Given Any Exam Yet.","Error!",JOptionPane.ERROR_MESSAGE);
//                return;
//            }
        //ArrayList<MyPayement> list=null;
         //StudentDetail sd=null;
             try {
             //list=StudentTransactionDao.getStudentTransactionDetails(contactNo);
            if(list.isEmpty())
            {
                //studentId.setText("");
                JOptionPane.showMessageDialog(null,"No Student in batch or below this fee");
                return;
            }
              System.out.println("Enter called");
               
               //studentId.setEnabled(false);
                
               //sd=StudentDetailDao.getStudentDetailsByContactNo(studentId.getText().substring(0,10));
               //sd.setStudentContact(studentId.getText().substring(0,10));
//               studentName.setText(sd.getStudentName().toUpperCase());
//               studentContact.setText(sd.getStudentContact());
//               studentEmail.setText(sd.getStudentEmail().toUpperCase());
//               studentCollage.setText(sd.getStudentCollege().toUpperCase());
//               studentSem.setText(sd.getStudentSem());
             // studentList.add(sd);
              
               //System.out.println(sd);
            } catch (Exception ex) {
                Logger.getLogger(PendingFeeDetails.class.getName()).log(Level.SEVERE, null, ex);
            }
             for(StudentTransaction tp:list){
            Object[] rows=new Object[7];                                                                                                                                      // 7 indicates the number of columns of table.
           
                rows[0]=tp.getTransactionId();
                rows[1]=tp.getEmpName();
                rows[2]=tp.getCentreId();
                rows[3]=tp.getGrossAmount();
                rows[4]=tp.getDateOfPayement();
               // rows[4]=st.getGrossAmount();
                
                model.addRow(rows);}
            
//        }
//        catch(SQLException e)
//        {
//            JOptionPane.showMessageDialog(null,"SQLException:"+e,"Error!",JOptionPane.ERROR_MESSAGE);
//            e.printStackTrace();
//        }
    }



}
