/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scaapp.gui;

import scaapp.pojo.EmployeeDetails;
import com.alee.laf.WebLookAndFeel;
import java.awt.Desktop;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.AbstractAction;
import javax.swing.ImageIcon;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.KeyStroke;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import scaapp.dao.BatchDao;
import scaapp.dao.EmployeeDao;
import scaapp.dao.SemesterReportDao;
import scaapp.gui.financemanager.ViewDayWiseFeeCollectionByCashier;
import scaapp.pojo.MyPayement;
import scaapp.pojo.ShowBatch;
import scaapp.pojo.StudentTransaction;

/**
 *
 * @author Comp10
 */
public class SemesterReportGeneration extends javax.swing.JFrame {

    /**
     * Creates new form ViewStudentDetails
     */
      ArrayList<StudentTransaction> list;
    private  DefaultTableModel model;
    private  DefaultTableModel model2;
   List<ShowBatch> batches;
     HashMap<String,ShowBatch> batchMap=new HashMap<>();
      HashMap<String,Integer> studentCount=null;
    EmployeeDetails ed;
      ImageIcon icon = new ImageIcon("src\\resources\\loading.gif");
    final JOptionPane optionPane = new JOptionPane("Loading.....", JOptionPane.NO_OPTION, JOptionPane.NO_OPTION, icon, new Object[]{}, icon);
    final JDialog dialog = new JDialog();
   
    public SemesterReportGeneration() {
        dialog.setContentPane(optionPane);
       
        dialog.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        dialog.pack();
        dialog.setLocationRelativeTo(SemesterReportGeneration.this);
        initComponents();
        mansarovar.setSelected(true);
        indrapuri.setSelected(true);
        jEmpList.addItem("All");
        this.model = (DefaultTableModel)jtMyPayement.getModel();
        this.model2 = (DefaultTableModel)jtMyPayement1.getModel();
         try {
            ArrayList <String> list=EmployeeDao.getAllFaculties();
            
            for(String s: list){
                
                jEmpList.addItem(s);
            }
          
        } catch (SQLException ex) {
            Logger.getLogger(ViewDayWiseFeeCollectionByCashier.class.getName()).log(Level.SEVERE, null, ex);
        }
        ArrayList<String> list=null;
        try {
            list = BatchDao.getAllBatchId();
        } catch (SQLException ex) {
            Logger.getLogger(SemesterReportGeneration.class.getName()).log(Level.SEVERE, null, ex);
        }
//         for(String s:list)
//               jcbatches.addItem(s);
//         minFee.requestFocus();
         setLocationRelativeTo(null);
         JPanel panel = (JPanel)this.getContentPane();
        InputMap im = panel.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        im.put(KeyStroke.getKeyStroke("ctrl pressed P"), "cP");
        panel.getActionMap().put("cP", new AbstractAction(){
            public void actionPerformed(ActionEvent e) {
                 SimpleDateFormat sdf=new SimpleDateFormat("yy-MM-dd");
           String start=sdf.format(awtStartDate.getDate());
           String end=sdf.format(awtEndDate.getDate());
        System.out.println(start);
        System.out.println(end);
        getData(start,end);
                print(start,end);
            }
        });
          setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
         
    }
    public SemesterReportGeneration(EmployeeDetails ed){
        this();
        this.ed=ed;
        employeeName2.setText(ed.getEmp_name());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtMyPayement = new javax.swing.JTable();
        export = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        awtStartDate = new com.toedter.calendar.JDateChooser();
        awtEndDate = new com.toedter.calendar.JDateChooser();
        mansarovar = new javax.swing.JCheckBox();
        indrapuri = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jEmpList = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        employeeName2 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tFee = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        totalStudent100Rs = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        JFeeLeft = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        totalStudentFeeCompleted = new javax.swing.JTextField();
        partialFeeStudent = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jtotalStudent = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtMyPayement1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Student Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jLabel5.setText("Name");

        jTextField5.setEnabled(false);

        jLabel6.setText("Email");

        jTextField6.setEnabled(false);

        jLabel7.setText("Semester");

        jTextField7.setEnabled(false);

        jLabel8.setText("College");

        jTextField8.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField7)
                    .addComponent(jTextField8))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Report Generator- SCAOnCloud v1.0.0");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Student who have paid partial Fees", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jtMyPayement.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtMyPayement.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Name", "Batch Id", "Left Fee", "Paid Amount", "Contact", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtMyPayement.setGridColor(new java.awt.Color(0, 0, 0));
        jtMyPayement.setOpaque(false);
        jScrollPane1.setViewportView(jtMyPayement);

        export.setText("Export");
        export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(export, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(export))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Batch/Fee details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        jPanel6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel6KeyPressed(evt);
            }
        });

        jLabel13.setText("End Date");

        jLabel14.setText("Start Date");

        mansarovar.setText("Mansarovar");
        mansarovar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mansarovarActionPerformed(evt);
            }
        });

        indrapuri.setText("Indrapuri");

        jLabel4.setText("Select Faculty");

        jEmpList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmpListActionPerformed(evt);
            }
        });

        jButton2.setText("Fetch data");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(awtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(63, 63, 63)
                        .addComponent(awtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mansarovar)
                    .addComponent(indrapuri)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jEmpList, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(awtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(awtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(mansarovar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(indrapuri))
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jEmpList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "User details"));

        jLabel18.setText("You are logged in as ");

        employeeName2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        employeeName2.setForeground(new java.awt.Color(0, 153, 51));
        employeeName2.setText("Paramjeet Singh");

        jButton8.setText("Logout");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Back");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(employeeName2)
                .addGap(108, 108, 108)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(employeeName2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addComponent(jButton9)
                .addGap(17, 17, 17)
                .addComponent(jButton8)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jLabel1.setText("Fee collected");

        tFee.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tFee.setEnabled(false);
        tFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFeeActionPerformed(evt);
            }
        });

        jLabel17.setText("100 Rs students");

        totalStudent100Rs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        totalStudent100Rs.setEnabled(false);
        totalStudent100Rs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalStudent100RsActionPerformed(evt);
            }
        });

        jLabel15.setText("Fee Left");

        JFeeLeft.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JFeeLeft.setEnabled(false);
        JFeeLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFeeLeftActionPerformed(evt);
            }
        });

        jLabel19.setText("Fee completed students");

        totalStudentFeeCompleted.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        totalStudentFeeCompleted.setEnabled(false);
        totalStudentFeeCompleted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalStudentFeeCompletedActionPerformed(evt);
            }
        });

        partialFeeStudent.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        partialFeeStudent.setEnabled(false);
        partialFeeStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partialFeeStudentActionPerformed(evt);
            }
        });

        jLabel20.setText("Partial fee students");

        jtotalStudent.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtotalStudent.setEnabled(false);
        jtotalStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtotalStudentActionPerformed(evt);
            }
        });

        jLabel16.setText("Total students");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JFeeLeft, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(jtotalStudent)
                    .addComponent(tFee))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(partialFeeStudent)
                            .addComponent(totalStudent100Rs, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalStudentFeeCompleted)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(totalStudent100Rs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(JFeeLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(totalStudentFeeCompleted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jtotalStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(partialFeeStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Batch Started Between Dates", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jtMyPayement1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtMyPayement1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Batch Id", "Collected Fee", "Faculty", "Course", "Centre", "Days", "Start date", "Total Students"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtMyPayement1.setGridColor(new java.awt.Color(0, 0, 0));
        jtMyPayement1.setOpaque(false);
        jScrollPane2.setViewportView(jtMyPayement1);

        jButton1.setText("Export");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         //getData();
        
          if(awtStartDate.getDate()==null){
            JOptionPane.showMessageDialog(null,"Please Select date","Error",JOptionPane.INFORMATION_MESSAGE);
            return;
        
        }   
          if(awtEndDate.getDate()==null){
            JOptionPane.showMessageDialog(null,"Please Select date","Error",JOptionPane.INFORMATION_MESSAGE);
            return;
        
        }   
            if(!mansarovar.isSelected()&&!indrapuri.isSelected())
        {
             JOptionPane.showMessageDialog(null,"Please Select atleast One Centre","Error",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
         SimpleDateFormat sdf=new SimpleDateFormat("yy-MM-dd");
           String start=sdf.format(awtStartDate.getDate());
           String end=sdf.format(awtEndDate.getDate());
        System.out.println(start);
        System.out.println(end);
        getData(start,end);
       
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jPanel6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel6KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6KeyPressed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
          ProfilesSelector mf=new ProfilesSelector(ed);
            mf.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
          new Login().setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void mansarovarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mansarovarActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_mansarovarActionPerformed

    private void exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportActionPerformed
        // TODO add your handling code here:
//         if(model.getRowCount()==0)
//            return;
          try{
     JFileChooser fileChooser = new JFileChooser();
     UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
      SwingUtilities.updateComponentTreeUI(fileChooser);
       // btn = jbutton varaiable name
    int retval = fileChooser.showSaveDialog(export);

    if (retval == JFileChooser.APPROVE_OPTION) {
        File file = fileChooser.getSelectedFile();
        if (file != null) {
            if (!file.getName().toLowerCase().endsWith(".xls")) {
                file = new File(file.getParentFile(), file.getName() + ".xls");



            }

            try {
                ExcelExporter exp=new ExcelExporter();
                // tabl = jtable variable name
                exp.exportTable(jtMyPayement, file);


                Desktop.getDesktop().open(file);
            } catch (UnsupportedEncodingException e) {
                e.printStackTrace();

            } catch (FileNotFoundException e) {
                e.printStackTrace();
                System.out.println("not found");
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        }


   }catch(Exception e){
       System.out.println("shit"+e);
       e.printStackTrace();
   }

        
        
    }//GEN-LAST:event_exportActionPerformed

    private void jEmpListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmpListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmpListActionPerformed

    private void tFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFeeActionPerformed

    private void JFeeLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFeeLeftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JFeeLeftActionPerformed

    private void jtotalStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtotalStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtotalStudentActionPerformed

    private void totalStudent100RsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalStudent100RsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalStudent100RsActionPerformed

    private void totalStudentFeeCompletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalStudentFeeCompletedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalStudentFeeCompletedActionPerformed

    private void partialFeeStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partialFeeStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_partialFeeStudentActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          // TODO add your handling code here:
//         if(model.getRowCount()==0)
//            return;
          try{
     JFileChooser fileChooser = new JFileChooser();
     UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
      SwingUtilities.updateComponentTreeUI(fileChooser);
       // btn = jbutton varaiable name
    int retval = fileChooser.showSaveDialog(export);

    if (retval == JFileChooser.APPROVE_OPTION) {
        File file = fileChooser.getSelectedFile();
        if (file != null) {
            if (!file.getName().toLowerCase().endsWith(".xls")) {
                file = new File(file.getParentFile(), file.getName() + ".xls");



            }

            try {
                ExcelExporter exp=new ExcelExporter();
                // tabl = jtable variable name
                exp.exportTable(jtMyPayement1, file);


                Desktop.getDesktop().open(file);
            } catch (UnsupportedEncodingException e) {
                e.printStackTrace();

            } catch (FileNotFoundException e) {
                e.printStackTrace();
                System.out.println("not found");
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        }


   }catch(Exception e){
       System.out.println("shit"+e);
       e.printStackTrace();
   }

        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SemesterReportGeneration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SemesterReportGeneration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SemesterReportGeneration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SemesterReportGeneration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                WebLookAndFeel.install();
                new SemesterReportGeneration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JFeeLeft;
    private com.toedter.calendar.JDateChooser awtEndDate;
    private com.toedter.calendar.JDateChooser awtStartDate;
    private javax.swing.JLabel employeeName2;
    private javax.swing.JButton export;
    private javax.swing.JCheckBox indrapuri;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jEmpList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTable jtMyPayement;
    private javax.swing.JTable jtMyPayement1;
    private javax.swing.JTextField jtotalStudent;
    private javax.swing.JCheckBox mansarovar;
    private javax.swing.JTextField partialFeeStudent;
    private javax.swing.JTextField tFee;
    private javax.swing.JTextField totalStudent100Rs;
    private javax.swing.JTextField totalStudentFeeCompleted;
    // End of variables declaration//GEN-END:variables
private void showDataInTable(ArrayList<MyPayement> data,HashMap<String,Integer> leftFeeMap,HashMap<String,Integer> paidFeeMap)
    {
     model.setRowCount(0);
     model2.setRowCount(0);
//        try
//        {
//            ArrayList<Performance> performanceList=PerformanceDAO.getAllData();
//            if(performanceList.isEmpty())
//            {
//                JOptionPane.showMessageDialog(null,"Sorrry! No STudent Has Given Any Exam Yet.","Error!",JOptionPane.ERROR_MESSAGE);
//                return;
//            }
        //ArrayList<MyPayement> list=null;
         //StudentDetail sd=null;
             try {
             //list=StudentTransactionDao.getStudentTransactionDetails(contactNo);
            if(data.isEmpty())
            {
                //studentId.setText("");
                JOptionPane.showMessageDialog(null,"No data in list");
                return;
            }
              System.out.println("Enter called");
               
               //studentId.setEnabled(false);
                
               //sd=StudentDetailDao.getStudentDetailsByContactNo(studentId.getText().substring(0,10));
               //sd.setStudentContact(studentId.getText().substring(0,10));
//               studentName.setText(sd.getStudentName().toUpperCase());
//               studentContact.setText(sd.getStudentContact());
//               studentEmail.setText(sd.getStudentEmail().toUpperCase());
//               studentCollage.setText(sd.getStudentCollege().toUpperCase());
//               studentSem.setText(sd.getStudentSem());
             // studentList.add(sd);
              
               //System.out.println(sd);
            } catch (Exception ex) {
                Logger.getLogger(SemesterReportGeneration.class.getName()).log(Level.SEVERE, null, ex);
            }
             SimpleDateFormat sdf=new SimpleDateFormat("yy-MM-dd");
             SimpleDateFormat sdf2=new SimpleDateFormat("dd-MM-yyyy");
          
             for(MyPayement st:data){
                
            Object[] rows=new Object[7];                                                                                                                                      // 7 indicates the number of columns of table.
           
                rows[0]=st.getStudentName();
                rows[1]=st.getBatchId();
                rows[2]=st.getGrossAmount();
                rows[3]=st.getCourseFee()-st.getGrossAmount();
                rows[4]=st.getStudentContactNo();
                 rows[5]=st.getEmail();
        
               
                model.addRow(rows);
             }
            
             for(ShowBatch s: batches){
              
                  Object[] rows=new Object[8];                                                                                                                                      // 7 indicates the number of columns of table.

                rows[0]=s.getBatchid();
                rows[1]=s.getFee();
                rows[2]=s.getFaculty();
                rows[3]=s.getCourse();
                 rows[4]=s.getCenter();
                  rows[5]=s.getDays();
                   rows[6]=s.getStart();
                   rows[7]=s.getStudents();
                model2.addRow(rows);}
             
            
//        }
//        catch(SQLException e)
//        {
//            JOptionPane.showMessageDialog(null,"SQLException:"+e,"Error!",JOptionPane.ERROR_MESSAGE);
//            e.printStackTrace();
//        }
    }

private void getData(String start,String end){
    dialog.setVisible(true);
    int feeCollected=0;
    int feeLeft=0;
    int student100rs=0;
    int totalStudent=0;
    int feeNotCompletedStudents=0;
    ArrayList<MyPayement> data=null;
    HashMap<String,Integer> leftFeeMap=null;
    HashMap<String,Integer> paidFeeMap=null;
    
   
  
   try {
     
        tFee.setText("");
        JFeeLeft.setText("");
        jtotalStudent.setText("");
        totalStudent100Rs.setText("");
        totalStudentFeeCompleted.setText("");
        partialFeeStudent.setText("");
        studentCount=SemesterReportDao.getStudentCountBatchWise(start,end);
      batches=SemesterReportDao.showRecords(start,end);
       if(jEmpList.getSelectedItem().toString().equalsIgnoreCase("All")){
           System.out.println("857");
             if(mansarovar.isSelected()&&indrapuri.isSelected()){
               feeCollected=SemesterReportDao.getTotalCollectedFee(start, end);
               feeLeft=SemesterReportDao.getTotalLeftFee(start, end);
               totalStudent=SemesterReportDao.getTotalStudents(start, end);
               student100rs=SemesterReportDao.getTotalStudentsWhoPaid100Rs(start, end);
               feeNotCompletedStudents=SemesterReportDao.getTotalStudentsWhoHaveNotCompletedFee(start, end);
                data= SemesterReportDao.getPendingPayement(start,end);
                  
              
             }
             else if(mansarovar.isSelected())
               {
               feeCollected=SemesterReportDao.getTotalCollectedFee(start, end,1);
               feeLeft=SemesterReportDao.getTotalLeftFee(start, end,1);
               totalStudent=SemesterReportDao.getTotalStudents(start, end,1);
               student100rs=SemesterReportDao.getTotalStudentsWhoPaid100Rs(start, end,1);
                feeNotCompletedStudents=SemesterReportDao.getTotalStudentsWhoHaveNotCompletedFee(start, end,1);
                data= SemesterReportDao.getPendingPayementCentreWise(start,end,1);
                batches=batches.stream().filter(s->s.getCenter().equalsIgnoreCase("mansarovar")).collect(Collectors.toList());
               
             }
             else if(indrapuri.isSelected())
               {
               feeCollected=SemesterReportDao.getTotalCollectedFee(start, end,2);
               feeLeft=SemesterReportDao.getTotalLeftFee(start, end,2);
               totalStudent=SemesterReportDao.getTotalStudents(start, end,2);
               student100rs=SemesterReportDao.getTotalStudentsWhoPaid100Rs(start, end,2);
               feeNotCompletedStudents=SemesterReportDao.getTotalStudentsWhoHaveNotCompletedFee(start, end,2);
               data= SemesterReportDao.getPendingPayementCentreWise(start,end,2);
               batches=batches.stream().filter(s->s.getCenter().equalsIgnoreCase("indrapuri")).collect(Collectors.toList());
          
            
               }
                 }  
             else{
             int eid=EmployeeDao.getEmployeeId(jEmpList.getSelectedItem().toString());
                 System.out.println("On 865");
             if(mansarovar.isSelected()&&indrapuri.isSelected()){
               feeCollected=SemesterReportDao.getTotalCollectedFeeBothCentre(start, end,eid);
               feeLeft=SemesterReportDao.getTotalLeftFeeBothCentre(start, end,eid);
               totalStudent=SemesterReportDao.getTotalStudentsBothCentre(start, end,eid);
               student100rs=SemesterReportDao.getTotalStudentsWhoPaid100RsBothCentre(start, end,eid);
               feeNotCompletedStudents=SemesterReportDao.getTotalStudentsWhoHaveNotCompletedFeeBothCentre(start, end,eid);
               data= SemesterReportDao.getPendingPayement(eid,start,end);
              batches=batches.stream().filter(s->s.getFaculty().equalsIgnoreCase(jEmpList.getSelectedItem().toString())).collect(Collectors.toList());       
                
             }
             else if(mansarovar.isSelected()){
                  feeCollected=SemesterReportDao.getTotalCollectedFee(start, end,1,eid);
               feeLeft=SemesterReportDao.getTotalLeftFee(start, end,1,eid);
               totalStudent=SemesterReportDao.getTotalStudents(start, end,1,eid);
               student100rs=SemesterReportDao.getTotalStudentsWhoPaid100Rs(start, end,1,eid);
                feeNotCompletedStudents=SemesterReportDao.getTotalStudentsWhoHaveNotCompletedFee(start, end,1,eid);
                 data= SemesterReportDao.getPendingPayementCentreWise(start,end,1,eid);
                 batches=batches.stream().filter(s->s.getFaculty().equalsIgnoreCase(jEmpList.getSelectedItem().toString())).filter(s->s.getCenter().equalsIgnoreCase("mansarovar")).collect(Collectors.toList());       
              
             }
             else if(indrapuri.isSelected()){
                 feeCollected=SemesterReportDao.getTotalCollectedFee(start, end,2,eid);
               feeLeft=SemesterReportDao.getTotalLeftFee(start, end,2,eid);
               totalStudent=SemesterReportDao.getTotalStudents(start, end,2,eid);
               student100rs=SemesterReportDao.getTotalStudentsWhoPaid100Rs(start, end,2,eid);
                feeNotCompletedStudents=SemesterReportDao.getTotalStudentsWhoHaveNotCompletedFee(start, end,2,eid);
                   data= SemesterReportDao.getPendingPayementCentreWise(start,end,2,eid);
                 batches=batches.stream().filter(s->s.getFaculty().equalsIgnoreCase(jEmpList.getSelectedItem().toString())).filter(s->s.getCenter().equalsIgnoreCase("indrapuri")).collect(Collectors.toList());  
              
             }
             }
             //System.out.println(list);
   }   
   catch(Exception e){
       dialog.dispose();
       e.printStackTrace();
   }
   tFee.setText(""+feeCollected);
        JFeeLeft.setText(""+feeLeft);
        jtotalStudent.setText(""+totalStudent);
        totalStudent100Rs.setText(""+student100rs);
         totalStudentFeeCompleted.setText(""+(totalStudent-feeNotCompletedStudents));
         partialFeeStudent.setText(""+(feeNotCompletedStudents-student100rs));
         showDataInTable(data,leftFeeMap,paidFeeMap);       dialog.dispose();
         
}
private void print(String start,String end){
  
}

}
class DataHolder{
    double paidAmount=0;

    public double getPaidAmount() {
        return paidAmount;
    }

    public void setPaidAmount(double paidAmount) {
        this.paidAmount = paidAmount;
    }

    public double getLeftAmount() {
        return leftAmount;
    }

    public void setLeftAmount(double leftAmount) {
        this.leftAmount = leftAmount;
    }
    double leftAmount=0;
}