/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scaapp.gui;

import scaapp.pojo.EmployeeDetails;
import com.alee.laf.WebLookAndFeel;
import java.awt.AWTKeyStroke;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.KeyStroke;
import scaapp.dao.AttendanceDao;
import scaapp.dao.BatchDao;
import scaapp.dao.CourseDao;
import scaapp.dao.EmployeeDao;
import scaapp.dao.RegistrationDao;
import scaapp.dao.StudentDetailDao;
import scaapp.dao.StudentTransactionDao;
import scaapp.pojo.BatchDetailsDisplay;
import scaapp.pojo.ShowBatch;
import scaapp.pojo.StudentDetail;
import scaapp.pojo.StudentTotalFeeDetail;
import scaapp.pojo.StudentTransaction;
import scaapp.utils.BatchIdGenerator;
import scaapp.utils.GSTReceiptPrinter;
import scaapp.utils.InternetUtil;

/**
 *
 * @author Comp10
 */
public class TakeStudentAttendance extends javax.swing.JFrame {
    private final TakeStudentAttendance ens = this;
    /**
     * Creates new form EnrollNewStudent
     */
    
    int count=0;
    int EmployeeId;
    StudentDetail sd;
    boolean first=true;
    EmployeeDetails ed;
    
//     @Override
//   public void setVisible(boolean val){
//       if(ed==null){
//        
//            JOptionPane.showMessageDialog(null,"Please Login First");
//            Login lp=new Login();
//            lp.setVisible(true);
//            this.dispose();
//            //return;
//       
//          
//       }
//       else{
//           super.setVisible(val);
//       }
//       
//   }
//    
    
    
    
    public TakeStudentAttendance() {
        initComponents();
        setLocationRelativeTo(null);
        JPanel panel = (JPanel)this.getContentPane();
        InputMap im = panel.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        im.put(KeyStroke.getKeyStroke("ctrl pressed B"), "cB");
        panel.getActionMap().put("cB", new AbstractAction(){
            public void actionPerformed(ActionEvent e) {
                ens.hide();
            }
        });
         im.put(KeyStroke.getKeyStroke("alt pressed C"), "ac");
        panel.getActionMap().put("ac", new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
             startSet();
            }
        });
        
      setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
         
//         batches.addItem("B0001-MSKJ630E17OCT18");
//         batches.addItem("B0002-MSKP430E03OCT18");
//         batches.addItem("B0003-MSSC530E13OCT18");
         
//        BatchIdGenerator big=new BatchIdGenerator();
//        big.setCenter(1);
//        big.setFaculty(EmployeeDao.getEmployeeId(null));
//        big.setCourse(awtCourse.getSelectedIndex()+1);
//        SimpleDateFormat sdf=new SimpleDateFormat(awtStartDate.getDateFormatString());
//        big.setTime(txtTime.getText());
//        big.setDate(awtStartDate.getDate());
//        String start=sdf.format(awtStartDate.getDate());
        //setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../resources/logo.png")));
    }

    TakeStudentAttendance(EmployeeDetails ed) {
       this();
       this.ed=ed;
       employeeName.setText(ed.getEmp_name());
       EmployeeId=ed.getEmp_id();
          ArrayList <String> batchesList=null;
        try {
            batchesList=BatchDao.getAllActiveBatchId(ed.getCentre_id());
        } catch (SQLException ex) {
            Logger.getLogger(FeePayment.class.getName()).log(Level.SEVERE, null, ex);
        }
         for(String s: batchesList)
          batches.addItem(s);
         
         batches.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        studentId = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        studentName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        studentEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        studentSem = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        studentCollage = new javax.swing.JTextField();
        studentContact = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Register = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        employeeName = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtcourseName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtBatchDays = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtBatchTime = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        batches = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jtBatchFaculty = new javax.swing.JTextField();
        lock = new javax.swing.JCheckBox();
        lockVisual = new javax.swing.JLabel();
        success = new javax.swing.JLabel();
        fail = new javax.swing.JLabel();
        paid = new javax.swing.JLabel();
        complete = new javax.swing.JLabel();
        notComplete = new javax.swing.JLabel();
        dueFee = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setTitle("Take attendance - SCAOnCloud v1.0.0");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Contact details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jLabel1.setText("Contact number/Barcode");

        studentId.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        studentId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIdActionPerformed(evt);
            }
        });
        studentId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                studentIdKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(studentId, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(studentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Student Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jLabel5.setText("Name");

        studentName.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        studentName.setEnabled(false);

        jLabel6.setText("Email");

        studentEmail.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        studentEmail.setEnabled(false);

        jLabel7.setText("Semester");

        studentSem.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        studentSem.setEnabled(false);

        jLabel8.setText("College");

        studentCollage.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        studentCollage.setEnabled(false);

        studentContact.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        studentContact.setEnabled(false);

        jLabel11.setText("Contact Number");

        Register.setText("Take attendence");
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });
        Register.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                RegisterKeyPressed(evt);
            }
        });

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Register)
                        .addGap(24, 24, 24)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(studentContact, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addComponent(studentEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addComponent(studentName, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(studentSem)
                        .addComponent(studentCollage)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(studentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(studentEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(studentContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(studentSem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(studentCollage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Register)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "User details"));

        jLabel16.setText("You are logged in as ");

        employeeName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        employeeName.setForeground(new java.awt.Color(0, 153, 51));
        employeeName.setText("Anonymous");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(employeeName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(employeeName))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Batch details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        jLabel2.setText("Course");

        jtcourseName.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtcourseName.setEnabled(false);

        jLabel3.setText("Days");

        jtBatchDays.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtBatchDays.setEnabled(false);

        jLabel4.setText("Time");

        jtBatchTime.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtBatchTime.setEnabled(false);

        jLabel9.setText("Batch code");

        batches.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                batchesItemStateChanged(evt);
            }
        });
        batches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchesActionPerformed(evt);
            }
        });
        batches.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                batchesKeyPressed(evt);
            }
        });

        jLabel10.setText("Faculty");

        jtBatchFaculty.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtBatchFaculty.setEnabled(false);

        lock.setText("Lock this batch for Attendence");
        lock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lockActionPerformed(evt);
            }
        });

        lockVisual.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lockVisual.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(lockVisual, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lock, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(jtcourseName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtBatchDays, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtBatchTime, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(batches, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtBatchFaculty))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(batches, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtcourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtBatchDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtBatchTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtBatchFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lockVisual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        success.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        success.setForeground(new java.awt.Color(0, 153, 0));
        success.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        fail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fail.setForeground(new java.awt.Color(255, 0, 0));
        fail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        paid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        paid.setForeground(new java.awt.Color(0, 204, 0));

        complete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        complete.setForeground(new java.awt.Color(102, 204, 0));

        notComplete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        notComplete.setForeground(new java.awt.Color(255, 51, 51));

        dueFee.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dueFee.setForeground(new java.awt.Color(255, 0, 0));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/plus.png"))); // NOI18N
        jMenu1.setText("New");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/user.png"))); // NOI18N
        jMenuItem6.setText("Enroll student");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/plus.png"))); // NOI18N
        jMenuItem3.setText("Add new student");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/rupee.png"))); // NOI18N
        jMenu2.setText("Fee");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/give-money.png"))); // NOI18N
        jMenuItem7.setText("Collect fees");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/time-left.png"))); // NOI18N
        jMenuItem9.setText("Pending fees");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/print.png"))); // NOI18N
        jMenu3.setText("Print");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/id-card.png"))); // NOI18N
        jMenuItem1.setText("ID card");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/id-card.png"))); // NOI18N
        jMenuItem2.setText("Print Id Of Full Batch");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/id-card.png"))); // NOI18N
        jMenuItem12.setText("Duplicate Reciept");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem12);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/eye-open.png"))); // NOI18N
        jMenu4.setText("View");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/user.png"))); // NOI18N
        jMenuItem4.setText("Student details");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/document.png"))); // NOI18N
        jMenuItem5.setText("Daily Collection");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuItem13.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/document.png"))); // NOI18N
        jMenuItem13.setText("Take Attendance");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem13);

        jMenuItem14.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/document.png"))); // NOI18N
        jMenuItem14.setText("View Attendance");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem14);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/lock.png"))); // NOI18N
        jMenu5.setText("Private");

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logout.png"))); // NOI18N
        jMenuItem11.setText("Logout");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem11);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/reload.png"))); // NOI18N
        jMenuItem8.setText("Change password");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem8);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(success, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                            .addComponent(fail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dueFee, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                            .addComponent(paid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(notComplete, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                            .addComponent(complete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(success, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fail, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(notComplete, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                            .addComponent(dueFee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(paid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(7, 7, 7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(complete, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                                .addContainerGap())))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentIdActionPerformed

    private void studentIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentIdKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
           
            
            doTask();
            
         
             
             
         }  

    }//GEN-LAST:event_studentIdKeyPressed

    private void batchesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_batchesKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            
          
            studentId.requestFocus();
            
            
            
            //jButton1.requestFocus();
            
        }
          
    }//GEN-LAST:event_batchesKeyPressed

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed
        //register();
        doTask();
    }//GEN-LAST:event_RegisterActionPerformed

    private void RegisterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RegisterKeyPressed
        //JOptionPane.showMessageDialog(null,"printing");
    }//GEN-LAST:event_RegisterKeyPressed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
//        this.setVisible(false);
//        new MainFrame().setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyReleased

    private void batchesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_batchesItemStateChanged
        try {
            // TODO add your handling code here:
            BatchDetailsDisplay bdd=BatchDao.showRecord(batches.getSelectedItem().toString());
            
            jtcourseName.setText(bdd.getCourseName());
            jtBatchDays.setText(bdd.getBatchDays());
            jtBatchTime.setText(bdd.getBatchTime());
            jtBatchFaculty.setText(bdd.getFacultyName());
            
            System.out.println(bdd);
        } catch (SQLException ex) {
            Logger.getLogger(TakeStudentAttendance.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_batchesItemStateChanged

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
         new EnrollNewStudent(ed).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
new MainFrame(ed).setVisible(true);
        this.dispose();        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        new MainFrame(ed).setVisible(true);
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        new ViewStudentDetails(ed).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        new ViewDayWiseFeeCollectionByCashier(ed).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        new PendingFeeDetails(ed).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void batchesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_batchesActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
startSet();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        new StudentDetailsNew(ed).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void lockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lockActionPerformed
        // TODO add your handling code here:
        if(lock.isSelected())
        {
            lockVisual.setText("Locked");
            batches.setEnabled(false);
        }
        else
        {
            lockVisual.setText("");
            batches.setEnabled(true);
        }
        studentId.requestFocus();
    }//GEN-LAST:event_lockActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        System.out.println("Hello");
        new TakeStudentAttendance(ed).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:

        new ViewAttendance(ed).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
          new ChangePassword(ed).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new GenerateIDCardOfFullBatch(ed).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new GenerateIDCard(ed).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        new GenerateDuplicateReciept(ed).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TakeStudentAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TakeStudentAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TakeStudentAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TakeStudentAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                WebLookAndFeel.install();
                new TakeStudentAttendance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Register;
    private javax.swing.JComboBox batches;
    private javax.swing.JLabel complete;
    private javax.swing.JLabel dueFee;
    private javax.swing.JLabel employeeName;
    private javax.swing.JLabel fail;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jtBatchDays;
    private javax.swing.JTextField jtBatchFaculty;
    private javax.swing.JTextField jtBatchTime;
    private javax.swing.JTextField jtcourseName;
    private javax.swing.JCheckBox lock;
    private javax.swing.JLabel lockVisual;
    private javax.swing.JLabel notComplete;
    private javax.swing.JLabel paid;
    private javax.swing.JTextField studentCollage;
    private javax.swing.JTextField studentContact;
    private javax.swing.JTextField studentEmail;
    private javax.swing.JTextField studentId;
    private javax.swing.JTextField studentName;
    private javax.swing.JTextField studentSem;
    private javax.swing.JLabel success;
    // End of variables declaration//GEN-END:variables
public void startSet(){
     sd=null;
        studentName.setText("");
        studentContact.setText("");
        studentEmail.setText("");
        studentCollage.setText("");
        studentSem.setText("");
        //enterfee.setText("");
        studentId.setText("");
        //enterfee.setEnabled(false);
        studentId.setEnabled(true);
        studentId.requestFocus(true);
        batches.hidePopup();
}
//public void register(){
//    if(!InternetUtil.check())
//    {
//         JOptionPane.showMessageDialog(null,"Please check your Internet Connection","NO INTERNET",JOptionPane.ERROR_MESSAGE);
//         return;
//    }
//        
//        
//        
//        
//        
//      try {
//             if(RegistrationDao.isRegistered(studentId.getText().substring(0,10), batches.getSelectedItem().toString()))
//                 {
//                    JOptionPane.showMessageDialog(null,"Student Already Registered");
//                     studentId.setText("");
//                      studentId.setEnabled(true);
//                      studentId.requestFocus();
//                      startSet();
//                return;
//                 }
////                StudentTransactionDao.addStudentTransaction(st);
////                new GSTReceiptPrinter().printGstReciept(st,sd.getStudentName());
////                startSet();
//                
//                
//                
//                
//                // 
//            
//               String message="Register "+studentName.getText()+" in "+jtcourseName.getText()+" of "+jtBatchFaculty.getText()+" at "+jtBatchTime.getText()+" Batch-Id-"+batches.getSelectedItem().toString();
//               
//               
//               JOptionPane optionPane = new JOptionPane(message+"\n\nWould you like to confirm registration?", JOptionPane.QUESTION_MESSAGE, JOptionPane.YES_NO_OPTION);
//    JDialog dialog = optionPane.createDialog("Confirm Payment?");
//    Set<AWTKeyStroke> focusTraversalKeys = new HashSet<AWTKeyStroke>(dialog.getFocusTraversalKeys(0));
//    focusTraversalKeys.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_RIGHT, KeyEvent.VK_UNDEFINED));
//    dialog.setFocusTraversalKeys(0, focusTraversalKeys);
//    dialog.setVisible(true);
//    dialog.dispose();
//    
//        
//    Integer dialogResult = (Integer) optionPane.getValue();
//               
//               
//               
//              // int dialogResult = JOptionPane.showConfirmDialog (null, message+"\n\nWould you like to confirm registration?","Warning",JOptionPane.YES_NO_OPTION);
//if(dialogResult==null || dialogResult == JOptionPane.NO_OPTION || dialogResult == JOptionPane.CLOSED_OPTION){
//  // Saving code here
//     JOptionPane.showMessageDialog(null,"Transaction Cancelled!!");
//      studentId.setText("");
//                      studentId.setEnabled(true);
//                      studentId.requestFocus();
//                       startSet();
//    return;
//}
//               if(!InternetUtil.check())
//    {
//         JOptionPane.showMessageDialog(null,"Please check your Internet Connection","NO INTERNET",JOptionPane.ERROR_MESSAGE);
//         this.setEnabled(true);
//         return;
//    }
//                
//               //sd=StudentDetailDao.getStudentDetailsByContactNo(studentId.getText().substring(0,10));
//               sd.setStudentContact(studentId.getText().substring(0,10));
//               studentName.setText(sd.getStudentName().toUpperCase());
//               studentContact.setText(sd.getStudentContact());
//               studentEmail.setText(sd.getStudentEmail().toUpperCase());
//               studentCollage.setText(sd.getStudentCollege().toUpperCase());
//               studentSem.setText(sd.getStudentSem());
//               System.out.println(sd);
//            } catch (SQLException ex) {
//                Logger.getLogger(FeePayment.class.getName()).log(Level.SEVERE, null, ex);
//            }
////         if(first){
////            first=false;
////            return;
////                 }
//         
//             Date d=null;
//             try {
//          d=StudentTransactionDao.getDate();
//                 //st.setTransactionId("MN/2018-2019/1008");
//            } catch (SQLException ex) {
//                Logger.getLogger(FeePayment.class.getName()).log(Level.SEVERE, null, ex);
//            }
//            Calendar c=Calendar.getInstance();
//            c.setTime(d);
//            int year;
//             int month = c.get(Calendar.MONTH);
//                if(month>=3)
//                    year=c.get(Calendar.YEAR);
//                else
//                    year=c.get(Calendar.YEAR)-1;
//             int amount=Integer.parseInt(100+"");
//             StudentTransaction st=new StudentTransaction();
//             st.setEmployeeId(EmployeeId);
//             st.setStudentId(sd.getStudentContact());
//            
//             st.setPayementModeId(1);
//             st.setBatchId(batches.getSelectedItem().toString());
//             st.setCentreId(1);
//             st.setGrossAmount(amount);
//             st.setCgstAmount(amount*0.09);
//             st.setSgstAmount(amount*0.09);
//             st.setNetAmount(amount-(st.getSgstAmount()+st.getCgstAmount()));
//             SimpleDateFormat sdf=new SimpleDateFormat("yy-MM-dd");
//             String date=sdf.format(d);
//             st.setDateOfPayement(date);
//             if(!InternetUtil.check())
//                    {
//                    JOptionPane.showMessageDialog(null,"Please check your Internet Connection","NO INTERNET",JOptionPane.ERROR_MESSAGE);
//                    return;
//                    }
//               while(true){  
//            try {
//                st.setTransactionId("MN/"+year+"-"+(year+1)+"/"+StudentTransactionDao.getNewTransactionId(null));
//                System.out.println(st.getTransactionId());
//               // StudentTransactionDao.addStudentTransaction(st);
//               // RegistrationDao.registerStudentInBatch(st.getStudentId(), st.getBatchId());
//                RegistrationDao.registerStudentInBatch(st);//using batch update
//               // new GSTReceiptPrinter().printGstReciept(st,sd.getStudentName());
//               
//                
//                
//                
//                
//                // 
//            } catch (SQLException ex) {
//                if(ex.getMessage().contains("Duplicate entry")){
//                             System.out.println("Error due to Duplicate entry");
//                             continue;
//                         }
//                Logger.getLogger(FeePayment.class.getName()).log(Level.SEVERE, null, ex);
//            }
//                break;
//               }
//                String s=sd.getStudentName();
//                Runnable r=()-> new GSTReceiptPrinter().printGstReciept(st,s);
//                Thread t=new Thread(r);
//                t.start();
//                
//                startSet();
//            studentId.setText("");
//                      studentId.setEnabled(true);
//                      studentId.requestFocus();
//                      startSet();
//            
//}
public void doTask(){
       
            if(!(studentId.getText().length()==10||studentId.getText().length()==12))
            {
                JOptionPane.showMessageDialog(null,"Enter Valid Phone Number or barcode");
                studentId.setText("");
                //JOptionPane.showMessageDialog(null,"Student have not filled form Yet!!");
                studentId.requestFocus();
                return;
            }
             
                String s=studentId.getText().substring(0,10);
              Runnable r=()->{try {
               sd=StudentDetailDao.getStudentDetailsByContactNo(s);
              //System.out.println(sd);
            if(sd==null)
            {
                
                JOptionPane.showMessageDialog(null,"Student has not provided his basic details yet!!");
//                studentId.setText("");
//               studentId.requestFocus();
                return;
            }
            
            
             try {
           double d=StudentTransactionDao.getStudentTotalPaidFeeInSingleBatch(s,batches.getSelectedItem().toString());
            paid.setText("Fee Paid "+d);
            double tFee=CourseDao.getCourseFeeByBatchId(batches.getSelectedItem().toString());
            dueFee.setText("Fee Due "+(tFee-d));
              System.out.println("Enter called");
               if(tFee==d)
               {
                   complete.setText("Fee Completed");
                   notComplete.setText("");
                   dueFee.setText("");
               }
               else
               {
                   complete.setText("");
                   notComplete.setText("Fee Not Completed");
               }
               //studentId.setEnabled(false);
                
               //sd=StudentDetailDao.getStudentDetailsByContactNo(studentId.getText().substring(0,10));
               //sd.setStudentContact(studentId.getText().substring(0,10));
//               studentName.setText(sd.getStudentName().toUpperCase());
//               studentContact.setText(sd.getStudentContact());
//               studentEmail.setText(sd.getStudentEmail().toUpperCase());
//               studentCollage.setText(sd.getStudentCollege().toUpperCase());
//               studentSem.setText(sd.getStudentSem());
             // studentList.add(sd);
              
               //System.out.println(sd);
            } catch (SQLException ex) {
                Logger.getLogger(ViewStudentDetails.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            
            
                sd.setStudentContact(s);
               studentName.setText(sd.getStudentName().toUpperCase());
               studentContact.setText(sd.getStudentContact());
               studentEmail.setText(sd.getStudentEmail().toUpperCase());
               studentCollage.setText(sd.getStudentCollege().toUpperCase());
               studentSem.setText(sd.getStudentSem());   
                  
                  
                  
          if(!RegistrationDao.isRegistered(s, batches.getSelectedItem().toString()))
                 {
                    success.setText("");
                    fail.setText("Not Registered in this batch");
                     complete.setText("");
                   notComplete.setText("");
                   dueFee.setText("");
                   paid.setText("");
//                     studentId.setText("");
//                      studentId.setEnabled(true);
//                      studentId.requestFocus();
                     // startSet();
                return;
                 }
             
               
               
             
        
          
          
          
                 //st.setTransactionId("MN/2018-2019/1008");
            } catch (SQLException ex) {
                 success.setText("");
                 fail.setText("Something went wrong try again later");
                 complete.setText("");
                   notComplete.setText("");
                   dueFee.setText("");
                   paid.setText("");
//                 studentId.setText("");
//                      studentId.setEnabled(true);
//                      studentId.requestFocus();
                      //startSet();
                return;
            }
              
              try {
                   Date d=null;
            
          d=StudentTransactionDao.getDate();
          SimpleDateFormat sdf=new SimpleDateFormat("yy-MM-dd");
          String date=sdf.format(d);
          System.out.println(date);
          
          d=StudentTransactionDao.getDate();
          AttendanceDao.addAttendence(s, batches.getSelectedItem().toString(), date);
                 //st.setTransactionId("MN/2018-2019/1008");
            } catch (SQLException ex) {
                   success.setText("");
                 fail.setText("Attendence already Done!!");
//                 studentId.setText("");
//                      studentId.setEnabled(true);
//                      studentId.requestFocus();
                      //startSet();
                return;
            }
             success.setText("Attendence added successfully!!");
                 fail.setText("");
                
                      //startSet();
             
};
              Thread th=new Thread(r);
              th.start();
  studentId.setText("");
                      studentId.setEnabled(true);
                      studentId.requestFocus();
                      }

}
